name: quiz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.16.0
  firebase_database: ^9.0.13
  firebase_database_web: ^0.2.0+12
  flutter_svg: ^1.0.3
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  workmanager: ^0.4.1
  timezone: ^0.8.0
  flutter_local_notifications: ^9.5.2
  date_time_picker: ^2.1.0
  syncfusion_flutter_datepicker: ^20.1.52
  flutter_countdown_timer: ^4.1.0
  date_count_down: ^2.1.0
  numberpicker: ^2.1.1
  get: 4.6.1
  awesome_notifications: ^0.6.21

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6
  flutter_test: 
    sdk: flutter
flutter_native_splash:
  color: "#000000"
  image: assets/Rectangle_32_1_900.png

flutter: 
  uses-material-design: true
  assets:
     - assets/images/
  fonts:
    - family: Glory
      fonts:
        - asset: assets/fonts/Glory-Light.ttf
        - asset: assets/fonts/Glory-LightItalic.ttf
        - asset: assets/fonts/Glory-Medium.ttf
        - asset: assets/fonts/Glory-MediumItalic.ttf
        - asset: assets/fonts/Glory-Regular.ttf
        - asset: assets/fonts/Glory-SemiBold.ttf




